export const SET_SERVICE_CREATE_REQUEST = "SET_SERVICE_CREATE_REQUEST"
export const SET_SERVICE_CREATE_ERROR = "SET_SERVICE_CREATE_ERROR"
export const SET_SERVICE_CREATE_SUCCESS = "SET_SERVICE_CREATE_SUCCESS"

export const SET_SERVICE_UPDATE_REQUEST = "SET_SERVICE_UPDATE_REQUEST"
export const SET_SERVICE_UPDATE_ERROR = "SET_SERVICE_UPDATE_ERROR"
export const SET_SERVICE_UPDATE_SUCCESS = "SET_SERVICE_UPDATE_SUCCESS"

export const GET_ALL_SERVICE_REQUEST = "GET_ALL_SERVICE_REQUEST"
export const GET_ALL_SERVICE_SUCCESS = "GET_ALL_SERVICE_SUCCESS"
export const GET_ALL_SERVICE_ERROR = "GET_ALL_SERVICE_ERROR"

export const DELETE_SERVICE_REQUEST = "DELETE_SERVICE_REQUEST"
export const DELETE_SERVICE_SUCCESS = "DELETE_SERVICE_SUCCESS"
export const DELETE_SERVICE_ERROR = "DELETE_SERVICE_ERROR"

export const SET_SHOW_HIDE_SERVICE_WINDOW = "SET_SHOW_HIDE_SERVICE_WINDOW"
export const SET_ACTIVE_SERVICE_TAB = "SET_ACTIVE_SERVICE_TAB"
