export const SET_FIELD_UPDATE = "SET_FIELD_UPDATE"

export const SET_AI_BOT_DATA_WITH_VERSION =
  "SET_AI_BOT_DATA_WITH_VERSION"

export const SET_AI_BOT_UI_DATA = "SET_AI_BOT_UI_DATA"

export const SET_AI_BOT_DATA_AS_PRIMARY = "SET_AI_BOT_DATA_AS_PRIMARY"

export const SET_STATE_FROM_PROPS = "SET_STATE_FROM_PROPS"
