export const SET_COMPANY_CREATE_REQUEST = "SET_COMPANY_CREATE_REQUEST"
export const SET_COMPANY_CREATE_ERROR = "SET_COMPANY_CREATE_ERROR"
export const SET_COMPANY_CREATE_SUCCESS = "SET_COMPANY_CREATE_SUCCESS"

export const SET_COMPANY_UPDATE_REQUEST = "SET_COMPANY_UPDATE_REQUEST"
export const SET_COMPANY_UPDATE_ERROR = "SET_COMPANY_UPDATE_ERROR"
export const SET_COMPANY_UPDATE_SUCCESS = "SET_COMPANY_UPDATE_SUCCESS"

export const GET_ALL_COMPANY_REQUEST = "GET_ALL_COMPANY_REQUEST"
export const GET_ALL_COMPANY_SUCCESS = "GET_ALL_COMPANY_SUCCESS"
export const GET_ALL_COMPANY_ERROR = "GET_ALL_COMPANY_ERROR"


export const DELETE_COMPANY_REQUEST = "DELETE_COMPANY_REQUEST"
export const DELETE_COMPANY_SUCCESS = "DELETE_COMPANY_SUCCESS"
export const DELETE_COMPANY_ERROR = "DELETE_COMPANY_ERROR"

export const SET_SHOW_HIDE_COMPANY_WINDOW = 'SET_SHOW_HIDE_COMPANY_WINDOW'